In [40]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sbn

In [41]:
ecommData = pd.read_csv('data.csv', encoding = 'ISO-8859-1')

In [42]:
parse = lambda x: x[0]
ecommData['Date'] = ecommData['InvoiceDate'].str.findall("^.{8,10} ").apply(parse)
ecommData['Time'] = ecommData['InvoiceDate'].str.findall(" .{4,5}$").apply(parse)

In [43]:
ecommData.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

      InvoiceDate  UnitPrice  CustomerID         Country        Date   Time  
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  12/1/2010    8:26  
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  12/1/2010    8:26  
2  12/1/2010 8:26       2.75     17850.0  United Kingdom  12/1/2010    8:26  
3  12/1/2010 8:26       3.39     17850.0  United Kingdom  12/1/2010    8:26  
4  12/1/2010 8:26       3.39     17850.0  United Kingdom  12/1/2010    8:26

In [44]:
ecommData.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
Date                0
Time                0
dtype: int64

In [45]:
values = range(len(ecommData['Country'].unique()))

In [46]:
values[0]

0

In [47]:
D={}
for i in range(len(ecommData['Country'].unique())):
    D[ecommData['Country'].unique()[i]] = i

In [48]:
D

{'Australia': 2,
 'Austria': 20,
 'Bahrain': 23,
 'Belgium': 12,
 'Brazil': 33,
 'Canada': 31,
 'Channel Islands': 16,
 'Cyprus': 18,
 'Czech Republic': 30,
 'Denmark': 17,
 'EIRE': 6,
 'European Community': 35,
 'Finland': 22,
 'France': 1,
 'Germany': 4,
 'Greece': 24,
 'Hong Kong': 25,
 'Iceland': 15,
 'Israel': 21,
 'Italy': 11,
 'Japan': 14,
 'Lebanon': 27,
 'Lithuania': 13,
 'Malta': 36,
 'Netherlands': 3,
 'Norway': 5,
 'Poland': 9,
 'Portugal': 10,
 'RSA': 37,
 'Saudi Arabia': 29,
 'Singapore': 26,
 'Spain': 8,
 'Sweden': 19,
 'Switzerland': 7,
 'USA': 34,
 'United Arab Emirates': 28,
 'United Kingdom': 0,
 'Unspecified': 32}

In [49]:
ecommData.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

      InvoiceDate  UnitPrice  CustomerID         Country        Date   Time  
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  12/1/2010    8:26  
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  12/1/2010    8:26  
2  12/1/2010 8:26       2.75     17850.0  United Kingdom  12/1/2010    8:26  
3  12/1/2010 8:26       3.39     17850.0  United Kingdom  12/1/2010    8:26  
4  12/1/2010 8:26       3.39     17850.0  United Kingdom  12/1/2010    8:26

In [50]:
code = lambda x:D[x]
ecommData['CountryCode'] = ecommData['Country'].apply(code)


In [51]:
ecommData.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

      InvoiceDate  UnitPrice  CustomerID         Country        Date   Time  \
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  12/1/2010    8:26   
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  12/1/2010    8:26   
2  12/1/2010 8:26       2.75     17850.0  United Kingdom  12/1/2010    8:26   
3  12/1/2010 8:26       3.39     17850.0  United Kingdom  12/1/2010    8:26   
4  12/1/2010 8:26       3.39     17850.0  United Kingdom  12/1/2010    8:26   

   CountryCode  
0            0  
1            0  
2            0  
3            0  
4            0

In [55]:
a = np.linspace(1,9,10)

In [63]:
b = np.linspace(5,20,10)

In [64]:
c = np.linspace(5,6,10)

In [65]:
d = np.array([a,b,c])

In [71]:
d.sum(axis=1)

array([  50.,  125.,   55.])

In [78]:
a.dot(np.array([c,b]).T)

array([ 283.14814815,  747.22222222])

In [79]:
a

array([ 1.        ,  1.88888889,  2.77777778,  3.66666667,  4.55555556,
        5.44444444,  6.33333333,  7.22222222,  8.11111111,  9.        ])

In [81]:
a[1:4]

array([ 1.88888889,  2.77777778,  3.66666667])

In [101]:
ecommData.loc[ecommData['Quantity'].max(),['Country','Date']]

Country    United Kingdom
Date            2/3/2011 
Name: 80995, dtype: object

In [102]:
x = pd.DataFrame()

In [103]:
x.shape

(0, 0)